name: Deploy Application


on:
  push:
    branches:
      - master


jobs:
  created-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JavaScript
        run: |
          npm install
          npm run prod



