name: Deploy Application


on:
  push:
    branches:
      - master


jobs:
  created-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JavaScript
        run: |
          npm install
          npm run prod

      - name : Configure PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, tokenize, xml

      name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist


